openapi: "3.0.1"
info:
  title: Image Processor API
  version: 1.0.0
paths:
  /process:
    post:
      summary: Process an image
      responses:
        "200":
          description: Successful response
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_function_arn}/invocations
        httpMethod: POST
        type: aws_proxy
